### ISSUE TITLE
Broken URLs 

### ISSUE THREAD

**Issue by aagaardk** [AEStrategies/coding-challenge#1]
The URLs for the Data Engineer > Entity Resolution and Data Scientist > Flights links within the README files are broken.

![image](https://user-images.githubusercontent.com/16258980/156812392-a02f8e93-8d66-4d98-a3df-efb1bcb7e987.png)
![image](https://user-images.githubusercontent.com/16258980/156812317-7d39374d-ef67-418f-8b5d-04ad6c7c40b6.png)

**Comment by sizzick** [comment]
Fixed with commit [`831630b`]("https://github.com/AEStrategies/coding-challenge/commit/831630bd168410d1ae5454ec2afcdf75f6724c31")
